spring:
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-shop-g48-final
    username: "postgres"
    password: "248842"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 100
      driver-class-name: "org.postgresql.Driver"



